version: "3.2"
services:
  web:
    image: nginx
    ports:
      - 8000:80
    container_name: "web"
    restart: unless-stopped
    volumes:
      - ./build:/usr/share/nginx/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf